name: universal_platform
description: Replacement for dart.io.Platform class which works on Web as well as Desktop and Mobile.
version: 0.1.3
homepage: https://github.com/gskinnerTeam/flutter-universal-platform
author: Shawn <shawn@gskinner.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
